### ISSUE TITLE
How can I get the corresponding chapters file in "txt"?

### ISSUE THREAD

**Issue by dqqcasia** [getalp/multilingual-speech2speech-dataset#2]
When I run "scripts/force-align.py", I got this error:
IOError: [Errno 2] No such file or directory: 'English_English_Standard_Version____NT_Non-drama/B24___01_2John_______ENGESVN1DA.txt'

**Comment by mzboito** [comment]
Hi there! 
It seems the bible.is site changed their download format once again. Since they are not providing the chapter text with the audio files anymore, I pushed the raw text for all the languages into the repository. You can now retrieve them at dataset/**LANGUAGE**/raw_txt/. 
For instance, the file missing in your error message is available [here](https://github.com/getalp/mass-dataset/blob/master/dataset/english/raw_txt/B24___01_2John_______ENGESVN1DA.txt). 
If you wish to extend the dataset for new languages, you can retrieve the raw text from the html pages accessible from [here](https://www.faithcomesbyhearing.com/audio-bibles/bible-recordings). 
If you have any other problem, please don't hesitate in contact us again.
